var Subjects = [
  "Computer Networks",
  "Operating Systems",
  "Database Management Systems (DBMS)",
  "Software Engineering",
  "Web Development",
  "Artificial Intelligence and Machine Learning",
  "Cloud Computing",
  "Cybersecurity",
  "Compiler Design",
  "Internet of Things (IoT)",
  "Structural Analysis",
  "Surveying",
  "Geotechnical Engineering",
  "Construction Materials and Techniques",
  "Transportation Engineering",
  "Fluid Mechanics",
  "Environmental Engineering",
  "Water Resources Engineering",
  "Earthquake Engineering",
  "Building Design and Drawing",
  "Thermodynamics",
  "Fluid Mechanics",
  "Strength of Materials",
  "Theory of Machines",
  "Heat and Mass Transfer",
  "Manufacturing Processes",
  "Machine Design",
  "Automobile Engineering",
  "CAD/CAM",
  "Robotics",
  "Electrical Circuits",
  "Power Systems",
  "Electrical Machines",
  "Control Systems",
  "Signals and Systems",
  "Power Electronics",
  "Renewable Energy Systems",
  "High Voltage Engineering",
  "Electrical Measurement and Instrumentation",
  "Microprocessors and Microcontrollers",
]
module.exports= Subjects
